tra/routes/routes.py
# Common routes such as home or logging out
from ..models import Form
from flask import (
    redirect,
    request,
    session,
    render_template,
    flash,
    escape,
    Blueprint,
    url_for,
)

bp = Blueprint("main", __name__)


@bp.route("/")
def home():
    return redirect(url_for("admin.admin_login"))

@bp.route("/<code>")
def form(code):
    Form.query.filter_by(code=code).first_or_404() 
    return render_template("public/form.html")

@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("admin.admin_login"))

tra/templates/admin.html
{% extends 'base.html' %}

{% block content %}

<h1 class="title is-2">Admin Dashboard</h1>
<hr class="title-hr">
<div class="container mb-4">
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="notification {{ category }} is-light animate__animated animate__backInRight"
      style="padding: 2rem; margin-top: 0px; margin-bottom: 0px;" role="alert">
      <button class="delete"></button>
      {{message}}
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}
</div>
<div id="dash-tabs" class="container">
    <div class="tabs is-large is-boxed">
        <ul>
            <!--The onload is to add data to each tab allowing access to it in main.js-->
            <li id="scouts" class="is-active"><a>Scouts</a></li>
            <li id="forms"><a>Forms</a></li>
            <li id="data"><a>Data</a></li>
            <li id="settings"><a>Settings</a></li>
        </ul>
    </div>

</div>

<section id="scouts-tab">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="add-scout-panel ">
                    <input id="new-name" name="name" class="input is-primary" type="text" placeholder="Scout Name">
                    <input id="new-code" name="code" class="input is-primary" type="password" placeholder="Scout Code">
                    <div class="is-flex is-justify-content-right">
                        <button id="create-new" class="button is-primary" disabled>+ New Scout</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="scout-cards" class="columns is-centered">
            <div class="column">
                {% for scout in scouts %}
                    <div class="scout-card">
                        <span class="name">{{ scout.name }}</span>
                        <div class="is-flex is-justify-content-right">
                            <a class="button is-info">View Responses</a>
                            <!--This is a false error. It does actually properly format-->
                            <a onclick="deleteScout({{ scout.id }})" class="button is-danger">Delete</a>
                        </div>
                    </div>
                {% else %}
                    No scouts
                {% endfor %}

            </div>
        </div>
    </div>
</section>
<section id="forms-tab">
    <div class="container">
        <div class="columns is-centered">
            <div class="column">
                {% for form in forms %}
                   <div class="form-card">
                        <div class="is-flex is-justify-content-center">
                            {{ form.name }}
                        </div>
                   </div> 
                {% endfor %}
            </div>

        </div>
    </div>
</section>
<section id="data-tab">
    Data
</section>
<section id="settings-tab">
    Settings
</section>

{% endblock %}

tra/templates/base.html
<!DOCTYPE html>
<html>
  {% include 'header.html' %}

  <body>
    <div style="display: relative">
      <div
        x-data="notificationHandler()"
        class="notification noti-content"
        @notify.window="updateNoti($event)"
        :class="{ [type] : true, 'animated' : animated }"
      >
        <span x-text="text"></span>
      </div>
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <notify x-data x-init="notify('{{ message }}', '{{category}}')"></notify>
      {% endfor %} {% endif %} {% endwith %}
      <header>
        <nav
          class="navbar is-danger is-spaced has-shadow"
          style="font-size: 1.1rem; background-color: #9a3334"
          role="navigation"
          aria-label="main navigation"
        >
          <a
            role="button"
            class="navbar-burger"
            aria-label="menu"
            aria-expanded="false"
          >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
          <div id="main-menu" class="navbar-menu">
            <div class="navbar-start">
              <a
                class="navbar-item"
                href="/admin"
                style="font-size: 1.5rem"
              >
                The Red Alliance
              </a>
              {% if admin %}
              <a href="{{ url_for('main.logout') }}" class="navbar-item">
                Logout
              </a>
              {% endif %}
            </div>
          </div>
        </nav>
      </header>
    </div>
    <div x-data x-cloak>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

tra/templates/header.html
<!--Header file with imports + title-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="user-scalable=no, width=760, initial-scale=1, maximum-scale=1" />
  {% if title %}
  <title>{{title}} - The Red Alliance</title>
  {% else %}
  <title>The Red Alliance</title>
  <template></template>
  {% endif %}
  <!--CSS Styles. Bulma, Animate.css, and custom-->
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" />
  <link
    rel="stylesheet"
    href="{{ url_for('static', filename='node_modules/bulma/css/bulma.css')}}"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />

  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz@20..48"
  />
  <!-- alpine tooltip -->
  <script
    src="https://cdn.jsdelivr.net/npm/@ryangjchandler/alpine-tooltip@1.x.x/dist/cdn.min.js"
    defer
  ></script>
  <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/dist/tippy.css" />
  <!-- Alpine Mask Plugin -->
  <script defer src="https://unpkg.com/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>

  <!--Alpine JS-->
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <!-- Bulma js plugins  -->
  <script src="/static/bulmajs/dist/alert.js"></script>
  <!-- FA Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!--Main js file-->
  <script src="{{ url_for('static', filename='main.js') }}"></script>
  <script>
    // min sitewidth
    var siteWidth = 550;
    var scale = screen.width / siteWidth;
    // set initial scale dynamiclly
    document
      .querySelector('meta[name="viewport"]')
      .setAttribute(
        "content",
        "width=" + siteWidth + ", initial-scale=" + scale + ""
      );
  </script>
</head>

tra/templates/home.html
<html>
    {% include 'header.html'%}
    <body>
        <!--Obviously frontend needs to be done-->
        <a href="{{ url_for('admin.admin_page') }}">Admin</a>
    </body>
</html>

tra/templates/notification.html
<div class="container">
  <!--Alpine js notifications-->
  <div x-data="notifyHandler()" @notify.window="addNotification($event)">
    <template x-for="noti in notifications">
      <div @animationend="remove(noti)" :class="{ [noti.cat] : true, 'animate__backOutLeft' : noti.initialized }" class="notification is-light animate__animated animate__backInRight"
        style="padding: 2rem; margin-top: 0px; margin-bottom: 0px;" role="alert">
        <button @click="noti.initialized = true"  class="delete"></button>
        <span x-text="noti.msg"></span>
      </div>      
    </template>
  </div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <notify x-data x-init="$dispatch('notify', { msg : '{{message}}', category : '{{category}}' })"></notify>
      {% endfor %}
    {% endif %}
  {% endwith %}

</div>
<script>

function notifyHandler() {
  return {
    notifications : [],
    // takes in a 'notify' event with params 'msg' and 'category'
    addNotification(e) {
      this.notifications.push(
        notification(e.detail.msg, e.detail.category)
      );
    },
    remove(noti) {
      // if it is just being called on the first animation event dont do anything
      if (!noti.initialized) return null;
      this.notifications = this.notifications.filter((a) => a != noti)
    }
  }
}
function notification(msg, category) {
  return {
    initialized : false,
    msg : msg, // msg and cat are only needed for dynamic notifications
    cat : category,
    animationEnded() {
      if (this.initialized) {
        this.deleted = true;
      }
    }
  }
}
</script>

tra/templates/test.html
<!doctype html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
	</head>
	<body style="background-color:lightgrey;">
  
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <a class="navbar-brand" href="#">The Red Alliance</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">

		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Menu
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		          <a class="dropdown-item" href="/">Home</a>
		          <a class="dropdown-item" href="login">Login</a>
		          <div class="dropdown-divider"></div>
		          <a class="dropdown-item" href="logout">Logout</a>
		        </div>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="#" tabindex="-1" aria-disabled="false">something</a>
		      </li>
		    </ul>
		    <form class="form-inline my-2 my-lg-0">
		      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		    </form>
		  </div>
		</nav>

		<div class = "container-fluid">
			{% block content %}
			{% endblock %}
		</div>
		
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	</body>
</html>